[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
lightyear = { workspace = true }

serde = { workspace = true }
ron = { workspace = true }

protocol = { path = "../protocol" }
common = { path = "../common" }
